# Forzamos la carga del prefork y deshabilitamos otros
LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so

<IfModule mpm_event_module>
    LoadModule mpm_event_module /usr/lib/apache2/modules/mod_mpm_event.so
    # Esto es un truco: comentamos la carga si existe
</IfModule>